CC = ~/riscv/bin/riscv64-unknown-elf-gcc
CFLAGS = -g -Wall -Werror -std=c99 -march=rv32im -mabi=ilp32 -c 
OBJDUMP = ~/riscv/bin/riscv64-unknown-elf-objdump 
build:
	$(CC) $(CFLAGS) Overflow.c -o overflow-riscv64.o 
objdump:
	$(OBJDUMP) -d overflow-riscv64.o 
clean:
	rm -f overflow-riscv64.o 

