CC = ~/riscv/bin/riscv64-unknown-elf-gcc
CFLAGS = -g -Wall -Werror -std=c99  -Wno-main -Wno-error=unused-variable -march=rv32im -mabi=ilp32 -c
OBJDUMP = ~/riscv/bin/riscv64-unknown-elf-objdump
build:
	$(CC) $(CFLAGS) printfunc.c -o print.o 
objdump:
	$(OBJDUMP) -d print.o 
clean:
	rm -f print.o 
